site_name: Borne Arcade
site_description: Documentation complete du projet borne arcade

theme:
  name: readthedocs

nav:
  - Accueil: README_DOCS.md
  - Installation: INSTALLATION.md
  - Deploiement Git: DEPLOIEMENT_GIT.md
  - Documentation technique: DOCUMENTATION_TECHNIQUE.md
  - Ajouter un jeu: AJOUT_JEU.md
  - Utilisateur: UTILISATEUR.md
  - Style guide: STYLE_GUIDE.md